# Generated by Django 5.1 on 2024-11-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('nacionalidad', models.CharField(max_length=50, null=True, verbose_name='Nacionalidad')),
                ('tiene_premio_nobel', models.BooleanField(default=False, verbose_name='Tiene premio nobel?')),
            ],
            options={
                'verbose_name': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.autor')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda')),
            ],
            options={
                'verbose_name': 'Libro',
            },
        ),
    ]
