# Generated by Django 5.1 on 2024-11-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=7, verbose_name='Numero de Teléfono')),
            ],
        ),
    ]
