# Generated by Django 5.1 on 2024-11-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(max_length=7, verbose_name='Número de Teléfono'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='tienda.dueno'),
        ),
    ]
