# Generated by Django 5.1 on 2024-11-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_dueno_alter_tienda_telefono_tienda_dueno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Dueno',
            },
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='dueno',
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'Tienda'},
        ),
        migrations.AddField(
            model_name='tienda',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='tienda.usuario'),
        ),
        migrations.DeleteModel(
            name='Dueno',
        ),
    ]
